export const jobs = [
  { id: 1, title: "Frontend Intern", company: "Acme Corp", location: "Remote", type: "Internship" },
  { id: 2, title: "Web Developer", company: "Tech Solutions", location: "On-site", type: "Full-time" },
  { id: 3, title: "Backend Developer", company: "CodeCraft Labs", location: "Remote", type: "Full-time" },
  { id: 4, title: "UI/UX Designer", company: "Pixel Studio", location: "Hybrid", type: "Full-time" },
  { id: 5, title: "React Developer", company: "NextGen Tech", location: "Remote", type: "Contract" },
  { id: 6, title: "Node.js Intern", company: "DevHive", location: "On-site", type: "Internship" },
  { id: 7, title: "Full Stack Developer", company: "InnovateX", location: "Hybrid", type: "Full-time" },
  { id: 8, title: "Software Engineer", company: "CloudNova", location: "Remote", type: "Full-time" },
  { id: 9, title: "QA Tester", company: "BugTrack Systems", location: "On-site", type: "Contract" },
  { id: 10, title: "Mobile App Developer", company: "AppSphere", location: "Remote", type: "Full-time" },
  { id: 11, title: "DevOps Engineer", company: "InfraTech", location: "Hybrid", type: "Full-time" },
  { id: 12, title: "Data Analyst Intern", company: "Insight Analytics", location: "Remote", type: "Internship" },
  { id: 13, title: "Angular Developer", company: "BrightSoft", location: "On-site", type: "Full-time" },
  { id: 14, title: "Python Developer", company: "DataWave", location: "Hybrid", type: "Full-time" },
  { id: 15, title: "Java Developer", company: "CodeBase Systems", location: "Remote", type: "Full-time" },
  { id: 16, title: "Product Manager", company: "Visionary Labs", location: "Hybrid", type: "Full-time" },
  { id: 17, title: "Technical Support Engineer", company: "HelpDesk Pro", location: "On-site", type: "Full-time" },
  { id: 18, title: "Machine Learning Engineer", company: "AI Core", location: "Remote", type: "Full-time" },
  { id: 19, title: "Graphic Designer", company: "Creative Minds", location: "Hybrid", type: "Contract" },
  { id: 20, title: "Cybersecurity Analyst", company: "SecureNet", location: "Remote", type: "Full-time" },
  { id: 21, title: "Cloud Engineer", company: "SkyHigh Tech", location: "Remote", type: "Full-time" },
  { id: 22, title: "Business Analyst", company: "Enterprise Hub", location: "Hybrid", type: "Full-time" },
  { id: 23, title: "HR Intern", company: "PeopleFirst", location: "On-site", type: "Internship" },
  { id: 24, title: "Content Writer", company: "WriteRight", location: "Remote", type: "Contract" },
  { id: 25, title: "Digital Marketing Executive", company: "MarketGurus", location: "Hybrid", type: "Full-time" },
  { id: 26, title: "iOS Developer", company: "AppWorks", location: "Remote", type: "Full-time" },
  { id: 27, title: "Android Developer", company: "MobileHub", location: "On-site", type: "Full-time" },
  { id: 28, title: "Database Administrator", company: "DataSafe", location: "Hybrid", type: "Full-time" },
  { id: 29, title: "Game Developer", company: "PlayZone Studios", location: "Remote", type: "Contract" },
  { id: 30, title: "System Administrator", company: "NetCore IT", location: "On-site", type: "Full-time" },
  { id: 31, title: "Blockchain Developer", company: "CryptoTech", location: "Remote", type: "Full-time" },
  { id: 32, title: "Embedded Systems Engineer", company: "ChipLogic", location: "On-site", type: "Full-time" },
  { id: 33, title: "AR/VR Developer", company: "Immersive Labs", location: "Hybrid", type: "Contract" },
  { id: 34, title: "Technical Recruiter", company: "TalentBridge", location: "Remote", type: "Full-time" },
  { id: 35, title: "SEO Specialist", company: "SearchBoost", location: "Hybrid", type: "Full-time" },
  { id: 36, title: "Power BI Developer", company: "InsightPro", location: "Remote", type: "Contract" },
  { id: 37, title: "SAP Consultant", company: "ERP Solutions", location: "On-site", type: "Full-time" },
  { id: 38, title: "Salesforce Developer", company: "CRM Experts", location: "Hybrid", type: "Full-time" },
  { id: 39, title: "IT Support Intern", company: "TechAssist", location: "On-site", type: "Internship" },
  { id: 40, title: "Network Engineer", company: "ConnectX", location: "Hybrid", type: "Full-time" },
  { id: 41, title: "Ruby on Rails Developer", company: "RapidApps", location: "Remote", type: "Full-time" },
  { id: 42, title: "Go Developer", company: "FastTrack Systems", location: "Remote", type: "Full-time" },
  { id: 43, title: "C++ Developer", company: "CoreLogic", location: "On-site", type: "Full-time" },
  { id: 44, title: "Technical Writer", company: "DocuTech", location: "Remote", type: "Contract" },
  { id: 45, title: "Automation Test Engineer", company: "Testify QA", location: "Hybrid", type: "Full-time" },
  { id: 46, title: "Project Coordinator", company: "AgileWorks", location: "On-site", type: "Full-time" },
  { id: 47, title: "Flutter Developer", company: "CrossPlatform Inc", location: "Remote", type: "Full-time" },
  { id: 48, title: "MERN Stack Developer", company: "StackBridge", location: "Hybrid", type: "Full-time" },
  { id: 49, title: "Data Engineer", company: "BigData Corp", location: "Remote", type: "Full-time" },
  { id: 50, title: "AI Research Intern", company: "DeepThink Labs", location: "Remote", type: "Internship" },
  { id: 51, title: "ETL Developer", company: "Pipeline Systems", location: "Hybrid", type: "Full-time" },
  { id: 52, title: "Unity Developer", company: "GameForge", location: "Remote", type: "Contract" },
  { id: 53, title: "Penetration Tester", company: "CyberShield", location: "On-site", type: "Full-time" },
  { id: 54, title: "Solutions Architect", company: "TechArchitects", location: "Hybrid", type: "Full-time" },
  { id: 55, title: "Site Reliability Engineer", company: "ScaleOps", location: "Remote", type: "Full-time" },
  { id: 56, title: "Firmware Engineer", company: "EmbeddedX", location: "On-site", type: "Full-time" },
  { id: 57, title: "React Native Developer", company: "MobileNext", location: "Hybrid", type: "Full-time" },
  { id: 58, title: "IT Consultant", company: "GlobalTech Advisors", location: "Remote", type: "Contract" },
  { id: 59, title: "Junior Software Engineer", company: "LaunchPad Tech", location: "On-site", type: "Full-time" },
  { id: 60, title: "Scrum Master", company: "AgileSprint", location: "Hybrid", type: "Full-time" }
];
